baseURL = 'https://maladroit.dev/'
languageCode = 'en-us'
title = 'maladroit.dev'
theme = 'mal'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup.highlight]
  style = "rose-pine-moon"
